<?php
/**
 * Created by PhpStorm.
 * User: Shu
 * Date: 21/01/17
 * Time: 10:17 PM
 */

namespace backend\models;
use common\models\Constants;
use yii\base\Model;
use yii\data\ActiveDataProvider;

class PageSearch extends Page
{

    public function rules()
    {
        return [
            [['id'],'integer'],
            [['type','title','content','views','created_at','updated_at','user_id','status'],'safe'],
        ];
    }

    public function scenarios()
    {
        return Model::scenarios(); // TODO: Change the autogenerated stub
    }

    public function search($searchParam)
    {
        $query = Page::find()->where(['type'=>Constants::TYPE_PAGE]);

        $query->select([
            'post.*',
        ]);

        // add conditions that should always apply here
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'sort' =>
            [
                'defaultOrder' => 'created_at DESC'
            ]
        ]);

        $this->load($searchParam);

        if (!$this->validate()) {
            // uncomment the following line if you do not want to return any records when validation fails
            // $query->where('0=1');
            return $dataProvider;
        }

        // grid filtering conditions
        $query->andFilterWhere([
            'post.id' => $this->id,
            'post.updated_at' => $this->updated_at,
            'post.status' => $this->status,
            'post.user_id' => $this->user_id,
        ]);

        $query->andFilterWhere(['like', 'post.title', $this->title]);

        return $dataProvider;
    }
}