<?php
/**
 * Created by PhpStorm.
 * User: Shu
 * Date: 21/01/17
 * Time: 10:16 PM
 */

namespace backend\models;

use common\models\Post;
use common\models\Constants;

class Page extends Post
{
    const SCENARIO_PAGE_CREATE = "page_create";
    const SCENARIO_PAGE_UPDATE = "page_update";

    public function scenarios()
    {
        $scenarios = parent::scenarios(); // TODO: Change the autogenerated stub
        $scenarios[self::SCENARIO_PAGE_CREATE] = ['type','content','updated_at','created_at','slug','title','status','comment_allowed','user_id'];
        return $scenarios;
    }

    public function rules()
    {
        return
        [
            ['type','default','value'=>Constants::TYPE_PAGE,'on'=>self::SCENARIO_PAGE_CREATE],
            ['type','default','value'=>Constants::TYPE_POST,'on'=>self::SCENARIO_PAGE_UPDATE],
            ['user_id','default','value'=>\Yii::$app->user->id,'on'=>self::SCENARIO_PAGE_CREATE],
            ['user_id','default','value'=>\Yii::$app->user->id,'on'=>self::SCENARIO_PAGE_UPDATE],
            [['type', 'title', 'slug', 'user_id','content','status'], 'required'],
            [['content'], 'string'],
            [['views', 'comment_allowed', 'status', 'user_id', 'featured_image'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['type', 'title', 'slug'], 'string', 'max' => 255],
            [['slug'], 'unique']
        ];
    }

    public function doRegister()
    {
        $connection = \Yii::$app->db;
        $transaction = $connection->beginTransaction();

        try{
            $this->save(false);
            $transaction->commit();
        }

        catch (\Exception $e) {
            $transaction->rollBack();
            throw $e;
        } catch (\Throwable $e) {
            $transaction->rollBack();
            throw $e;
        }
    }
}