<?php
/**
 * Created by PhpStorm.
 * User: Shu
 * Date: 19/02/17
 * Time: 10:56 AM
 */

namespace frontend\widgets;
use frontend\models\Posts;
use yii\base\Widget;
use common\models\Constants;
use common\models\Category;

class FeaturedSectionWidget extends Widget
{
    public $post_model;
    public $options = [];
    public $enableCache = Constants::ENABLE_CACHE;

    public function init()
    {
        $db_model = new Posts();
        parent::init(); // TODO: Change the autogenerated stub

        $this->_setCategory();
        $this->_setPostCount();
        $this->_setTitle();

        if (is_array($this->options['category']) && sizeof($this->options['category']) > 0 ){
            $this->post_model = $db_model->getSetFeaturedPosts($this->options['category'],['count' => $this->options['count']]);
        } else{
            $this->post_model = $db_model->getSetRecentPosts();
        }
    }

    public function _setPostCount(){
        if (!isset($this->options['count'])){
            if (isset($this->options['type'])){
                $this->options['count'] = (int)\Yii::$app->params['settings']['sticky_widget_'.$this->options['type'].'_count'];
            }
            else{
                $this->options['count'] = (int)\Yii::$app->params['settings']['featured_widget_count'];
            }
        }
    }

    public function _setCategory(){
        if (!isset($this->options['category'])){
            if (isset($this->options['type'])){
                $this->options['category'] = unserialize(\Yii::$app->params['settings']['sticky_widget_'.$this->options['type'].'_category']);
            }
            else{
                $this->options['category'] = unserialize(\Yii::$app->params['settings']['featured_widget_category']);
            }
        }
    }

    public function _setTitle(){
        $this->options['title'] = "Featured Articles";

        if (isset($this->options['category']) && is_array($this->options['category'])){
            $categories = Category::find()->where(['id'=>$this->options['category']])->all();
            $title = [];
            foreach ($categories as $category)
            {
                $title[] = $category->name;
            }

            $this->options['title'] = implode(' & ', $title);
        }
    }

    private function getPostInformation($model){
        $posts_array = [];
        $model_size = sizeof($this->post_model);
        for ($i=0; $i<$this->options['count'] && $i < $model_size; $i++){
            if ($this->post_model[$i]){
                $posts_array[] = Posts::getPostInformation($this->post_model[$i]);
            }
        }
        return $posts_array;
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $post_array = $this->getPostInformation($this->post_model);
        $options['type'] = isset($this->options['type']) ? $this->options['type'] : '';
        echo $this->render('main_featured'.$options['type'].'.twig',[
            'post_model' => $post_array,
            'options' => $this->options,
        ]);
    }
}