<?php
/**
 * Created by PhpStorm.
 * User: Shu
 * Date: 19/02/17
 * Time: 10:56 AM
 */

namespace frontend\widgets;
use frontend\models\Posts;
use yii\base\Widget;
use common\models\Constants;
use common\models\Category;

class FeaturedSectionWidget extends Widget
{
    public $post_model;
    public $options = [];
    public $enableCache = Constants::ENABLE_CACHE;

    public function init()
    {
        $db_model = new Posts();
        parent::init(); // TODO: Change the autogenerated stub
        $this->options['type'] = isset($this->options['type']) ? $this->options['type'] : '';
        if ($this->options['type'] !== ''){
            $this->options['category'] = isset($this->options['category']) ? $this->options['category']  :  unserialize(\Yii::$app->params['settings']['sticky_widget_'.$this->options['type'].'_category']);
            $this->options['defaultTitle'] = isset($this->options['defaultTitle']) ? $this->options['defaultTitle'] : \Yii::$app->params['settings']['sticky_widget_'.$this->options['type'].'_default_title'];
            $this->options['count'] = isset($this->options['count']) ? $this->options['count']  :(int)\Yii::$app->params['settings']['sticky_widget_'.$this->options['type'].'_count'];
        }
        else{
            $this->options['category'] = isset($this->options['category']) ? $this->options['category']  :  unserialize(\Yii::$app->params['settings']['featured_widget_category']);
            $this->options['count'] = isset($this->options['count']) ? $this->options['count']  :(int)\Yii::$app->params['settings']['featured_widget_count'];
        }

        if (is_array($this->options['category']) && sizeof($this->options['category']) > 0 )
        {
            $this->post_model = $db_model->getSetFeaturedPosts($this->options['category'],[]);
            $this->options['title'] = $this->getTitle($this->options['category']);
        } else{
            $this->post_model = $db_model->getSetRecentPosts();
            $this->options['title'] = $this->options['defaultTitle'];
        }
    }

    public function getTitle($categories){
        $categories = Category::find()->where(['id'=>$categories])->all();
        $title = [];
        foreach ($categories as $category)
        {
            $title[] = $category->name;
        }
        return implode(' & ', $title);
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        return $this->render('main_featured'.$this->options['type'],[
            'post_model' => $this->post_model,
            'options' => $this->options
        ]);
    }
}