<?php
/**
 * Created by PhpStorm.
 * User: Shu
 * Date: 19/02/17
 * Time: 10:56 AM
 */

namespace frontend\widgets;
use yii\base\Widget;
use common\models\Post;
use common\models\Constants;

class FeaturedSectionWidget extends Widget
{
    public $post_model;
    public $category;
    public $count;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->category = $this->category ? $this->category  :  unserialize(\Yii::$app->params['settings']['featured_widget_category']);
        $this->count = $this->count ? $this->count  :(int)\Yii::$app->params['settings']['featured_widget_count'];

        if ($this->count >5){
            $this->count = 5;
        }
        if (is_array($this->category) && sizeof($this->category) > 0 )
        {
            $query = Post::find()->where(['type'=>Constants::TYPE_POST, 'status'=>Constants::DEFAULT_POST_STATUS]);
            $query->joinWith('postCategories cat');
            $query->andWhere(['category_id'=>$this->category]);

            $this->post_model = $query->orderBy('created_at DESC')->limit($this->count)->all();
        }

        else{
            $query = Post::find()->where(['type'=>Constants::TYPE_POST, 'status'=>Constants::DEFAULT_POST_STATUS]);
            $this->post_model = $query->orderBy('created_at DESC')->limit($this->count)->all();
        }
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        return $this->render('main_featured',[
            'post_model' => $this->post_model,
            'post_count' => $this->count
        ]);
    }
}