<?php
/**
 * Created by PhpStorm.
 * User: Shu
 * Date: 26/02/17
 * Time: 11:50 AM
 */

namespace frontend\widgets;
use common\models\Comment;
use common\models\Constants;
use yii\base\Widget;


class RecentCommentsWidget extends Widget
{
    public $postId;
    private $comment_model;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->comment_model = Comment::find()->where(['post_id' => $this->postId, 'status' => Constants::ACTIVE_COMMENT_STATUS])->orderBy('created_at DESC')->all();
    }

    public function run()
    {
        echo $this->render('recent_comment',[
            'comment_model' => $this->comment_model
        ]);
    }
}