<?php

namespace common\models;

use \common\models\base\Taxinomy as BaseTaxinomy;
use common\models\Constants;

/**
 * This is the model class for table "taxinomy".
 */
class Taxinomy extends BaseTaxinomy
{
    const SCENARIO_TAG_CREATEUPDATE = "tagCreateUpdate";

    public function scenarios()
    {
        $scenarios = parent::scenarios();
        $scenarios[self::SCENARIO_TAG_CREATEUPDATE] = ['value','type','created_at','updated_at','slug'];
        return parent::scenarios(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return
	    [
            ['type','default','value'=>Constants::TAXINOMY_TYPE_TAGS,'on'=>self::SCENARIO_TAG_CREATEUPDATE],
            ['value', 'filter', 'filter' => function ($value) {
                return ucfirst(strtolower(trim($value)));
            }],
            [['type', 'value'], 'required'],
            [['created_at', 'updated_at','slug'], 'safe'],
            [['type', 'value'], 'string', 'max' => 255],
            [['slug'], 'string', 'max' => 255],
            [['slug'], 'unique']
        ];
    }
	
}
