<?php

namespace common\models\base;

use Yii;

/**
 * This is the base model class for table "option".
 *
 * @property integer $id
 * @property string $name
 * @property string $value
 */
class Option extends \yii\db\ActiveRecord
{
    use \mootensai\relation\RelationTrait;

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['value'], 'string'],
            [['name'], 'string', 'max' => 255],
            [['name'], 'unique']
        ];
    }
    
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'option';
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'value' => 'Value',
        ];
    }

    public function beforeSave($insert)
    {
//        \Yii::$app->cache->delete('GLOBAL_SETTINGS');
          \Yii::$app->frontendCache->delete('GLOBAL_SETTINGS');

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
